import pygame
from Settings import *

class Bullet(pygame.sprite.Sprite):
    def __init__(self,globalX,globalY,speedX,speedY,damage,origin,orderNum):
        super().__init__()
        self.globalX=globalX
        self.globalY=globalY
        self.speedX=speedX
        self.speedY=speedY
        self.damage=damage
        self.orderNum=orderNum
        self.origin=origin # origin==0 means it is generated by monsters,and 1=>player
        self.image=pygame.transform.scale(pygame.image.load(BulletSettings.bulletImage)
                                          ,(BulletSettings.bulletWidth,BulletSettings.bulletHeight))
        self.rect=self.image.get_rect()
        self.rect.topleft=(self.globalX,self.globalY)
    
    def update(self):
        self.rect=self.rect.move(self.speedX,self.speedY)
        self.globalX+=self.speedX
        self.globalY+=self.speedY

class Weapon(pygame.sprite.Sprite):
    def __init__(self,weaponType,weaponLevel,xCoor,yCoor):
        super().__init__()
        self.level=weaponLevel
        self.weaponType=weaponType
        self.name=WeaponsSettings.weaponsName[weaponType]
        self.damage=WeaponsSettings.weaponsDamage[weaponType]
        self.mpCost=WeaponsSettings.weaponsMpCost[weaponType]
        self.name=WeaponsSettings.weaponsName[weaponType]
        self.damage=WeaponsSettings.weaponsDamage[weaponType]
        self.mpCost=WeaponsSettings.weaponsMpCost[weaponType]
        # image, width, height are under construction
        self.image=pygame.transform.scale(pygame.image.load(WeaponsSettings.images[weaponType])
                                          ,(WeaponsSettings.width[weaponType],WeaponsSettings.width[weaponType]))
        self.rect=self.image.get_rect()
        self.rect.topleft=(xCoor,yCoor)